{
  "formatVersion": "1.1",
  "component": {
    "group": "eu.axeptio",
    "module": "axeptio-sdk-sources",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5",
      "buildId": "d4et5qm5creabkykkuvsufodee"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "axeptio-sdk-sources-1.0.0.aar",
          "url": "axeptio-sdk-sources-1.0.0.aar",
          "size": 171193,
          "sha512": "37115113a2a16ce39cc122058d4ab18234a0d6c1b962830d88521db16fac90af80fd7233da4ff5d5e7716c67f507dd66f46271b879b391f05430abd0b0b04662",
          "sha256": "cf27f8ecede53427d205ab13fd33f0163b272c55d0948d132baf41504065012b",
          "sha1": "d627afcd10bfedc3db3e7ca661c9ae29f6c47b7c",
          "md5": "17d3d9b3f15b639fff29d8e5b37d3c7f"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.31"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel-android",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.github.kittinunf.fuel",
          "module": "fuel-gson",
          "version": {
            "requires": "2.3.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil",
          "version": {
            "requires": "1.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "axeptio-sdk-sources-1.0.0.aar",
          "url": "axeptio-sdk-sources-1.0.0.aar",
          "size": 171193,
          "sha512": "37115113a2a16ce39cc122058d4ab18234a0d6c1b962830d88521db16fac90af80fd7233da4ff5d5e7716c67f507dd66f46271b879b391f05430abd0b0b04662",
          "sha256": "cf27f8ecede53427d205ab13fd33f0163b272c55d0948d132baf41504065012b",
          "sha1": "d627afcd10bfedc3db3e7ca661c9ae29f6c47b7c",
          "md5": "17d3d9b3f15b639fff29d8e5b37d3c7f"
        }
      ]
    }
  ]
}
